#!/bin/sh

id logster 2>/dev/null
if [ $? -eq 0 ]; then
    echo "User 'logster' already exists! Skipping adduser ..."
    exit
fi

adduser --system --no-create-home --disabled-login --disabled-password --group logster

chown -R logster /usr/local/var/run/logster
chown -R root:logster /var/log/logster
chmod g+w /var/log/logster
