#!/bin/sh

id seo-monitoring 2>/dev/null
if [ $? -eq 0 ]; then
    echo "User 'seo-monitoring' already exists! Skipping adduser ..."
    exit
fi

adduser --system --no-create-home --disabled-login --disabled-password --group seo-monitoring

chown -R seo-monitoring /usr/local/var/run/logster
chown -R root:seo-monitoring /var/log/logster
chmod g+w /var/log/logster
